id: PYSEC-2013-2
details: lib/ansible/playbook/__init__.py in Ansible 1.2.x before 1.2.3, when playbook
  does not run due to an error, allows local users to overwrite arbitrary files via
  a symlink attack on a retry file with a predictable name in /var/tmp/ansible/.
affected:
- package:
    name: ansible
    ecosystem: PyPI
    purl: pkg:pypi:ansible
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: 1.2.0
    - fixed: 1.2.3
  versions:
  - "1.2"
  - 1.2.1
  - 1.2.2
references:
- type: REPORT
  url: https://bugzilla.redhat.com/show_bug.cgi?id=998227
- type: WEB
  url: http://www.ansible.com/security
- type: WEB
  url: https://exchange.xforce.ibmcloud.com/vulnerabilities/86898
- type: WEB
  url: https://groups.google.com/forum/#!topic/ansible-project/UVDYW0HGcNg
aliases:
- CVE-2013-4260
modified: "2021-07-02T02:41:32.973358Z"
published: "2013-09-16T19:14:00Z"
