id: PYSEC-0000-CVE-2018-10874
package:
  name: ansible
  ecosystem: PyPI
details: In ansible it was found that inventory variables are loaded from current
  working directory when running ad-hoc command which are under attacker's control,
  allowing to run arbitrary code as a result.
affects:
  ranges: 
  - type: ECOSYSTEM
    introduced: '0'
references:
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-10874
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2018:2166
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2018:2152
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2018:2151
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2018:2150
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2018:2321
- type: WEB
  url: http://www.securitytracker.com/id/1041396
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2018:2585
- type: WEB
  url: https://access.redhat.com/errata/RHBA-2018:3788
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2019:0054
- type: WEB
  url: https://usn.ubuntu.com/4072-1/
aliases:
- CVE-2018-10874
modified: "2019-07-25T02:15:00Z"
published: "2018-07-02T13:29:00Z"
