id: PYSEC-2020-202
details: Ansible before 1.5.5 constructs filenames containing user and password fields
  on the basis of deb lines in sources.list, which might allow local users to obtain
  sensitive credential information in opportunistic circumstances by leveraging existence
  of a file that uses the "deb http://user:pass@server:port/" format.
affected:
- package:
    name: ansible
    ecosystem: PyPI
    purl: pkg:pypi:ansible
  ranges:
  - type: GIT
    repo: https://github.com/ansible/ansible
    events:
    - introduced: "0"
    - fixed: c4b5e46054c74176b2446c82d4df1a2610eddc08
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 1.5.5
  versions:
  - "1.0"
  - "1.1"
  - "1.2"
  - 1.2.1
  - 1.2.2
  - 1.2.3
  - 1.3.0
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - 1.3.4
  - "1.4"
  - 1.4.1
  - 1.4.2
  - 1.4.3
  - 1.4.4
  - 1.4.5
  - "1.5"
  - 1.5.1
  - 1.5.2
  - 1.5.3
  - 1.5.4
references:
- type: WEB
  url: https://security-tracker.debian.org/tracker/CVE-2014-4660
- type: FIX
  url: https://github.com/ansible/ansible/commit/c4b5e46054c74176b2446c82d4df1a2610eddc08
- type: WEB
  url: https://www.securityfocus.com/bid/68231
- type: WEB
  url: https://www.openwall.com/lists/oss-security/2014/06/26/19
- type: WEB
  url: https://github.com/ansible/ansible/blob/release1.5.5/CHANGELOG.md
aliases:
- CVE-2014-4660
modified: "2021-07-02T02:41:33.239912Z"
published: "2020-02-20T03:15:00Z"
