id: PYSEC-0000-CVE-2018-16859
package:
  name: ansible
  ecosystem: PyPI
details: Execution of Ansible playbooks on Windows platforms with PowerShell ScriptBlock
  logging and Module logging enabled can allow for 'become' passwords to appear in
  EventLogs in plaintext. A local user with administrator privileges on the machine
  can view these logs and discover the plaintext password. Ansible Engine 2.8 and
  older are believed to be vulnerable.
affects:
  ranges:
  - type: ECOSYSTEM
    introduced: 2.7.0
    fixed: 2.7.4
  - type: ECOSYSTEM
    introduced: 2.7.5
    fixed: 2.8.1
  - type: ECOSYSTEM
    fixed: 2.5.13
  - type: ECOSYSTEM
    introduced: 2.6.0
    fixed: 2.6.10
references:
- type: WEB
  url: https://github.com/ansible/ansible/pull/49142
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2018-16859
- type: WEB
  url: http://www.securityfocus.com/bid/106004
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2018:3773
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2018:3772
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2018:3771
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2018:3770
- type: WEB
  url: http://lists.opensuse.org/opensuse-security-announce/2019-04/msg00021.html
- type: WEB
  url: http://lists.opensuse.org/opensuse-security-announce/2019-06/msg00077.html
- type: WEB
  url: http://lists.opensuse.org/opensuse-security-announce/2019-08/msg00020.html
aliases:
- CVE-2018-16859
modified: "2019-04-03T09:29:00Z"
published: "2018-11-29T18:29:00Z"
