id: PYSEC-0000-CVE-2016-8647
package:
  name: ansible
  ecosystem: PyPI
details: An input validation vulnerability was found in Ansible's mysql_user module
  before 2.2.1.0, which may fail to correctly change a password in certain circumstances.
  Thus the previous password would still be active when it should have been changed.
affects:
  ranges:
  - type: ECOSYSTEM
    fixed: 2.2.1.0
references:
- type: WEB
  url: https://github.com/ansible/ansible-modules-core/pull/5388
- type: WEB
  url: https://bugzilla.redhat.com/show_bug.cgi?id=CVE-2016-8647
- type: WEB
  url: https://access.redhat.com/errata/RHSA-2017:1685
aliases:
- CVE-2016-8647
modified: "2019-10-09T23:20:00Z"
published: "2018-07-26T14:29:00Z"
