id: PYSEC-2020-199
details: The safe_eval function in Ansible before 1.5.4 does not properly restrict
  the code subset, which allows remote attackers to execute arbitrary code via crafted
  instructions.
affected:
- package:
    name: ansible
    ecosystem: PyPI
    purl: pkg:pypi:ansible
  ranges:
  - type: ECOSYSTEM
    events:
    - introduced: "0"
    - fixed: 1.5.4
  versions:
  - "1.0"
  - "1.1"
  - "1.2"
  - 1.2.1
  - 1.2.2
  - 1.2.3
  - 1.3.0
  - 1.3.1
  - 1.3.2
  - 1.3.3
  - 1.3.4
  - "1.4"
  - 1.4.1
  - 1.4.2
  - 1.4.3
  - 1.4.4
  - 1.4.5
  - "1.5"
  - 1.5.1
  - 1.5.2
  - 1.5.3
references:
- type: WEB
  url: https://www.securityfocus.com/bid/68232
- type: WEB
  url: https://github.com/ansible/ansible/blob/release1.5.5/CHANGELOG.md
aliases:
- CVE-2014-4657
modified: "2021-07-02T02:41:33.107799Z"
published: "2020-02-20T15:15:00Z"
