id: PYSEC-0000-CVE-2021-41104
details: ESPHome is a system to control the ESP8266/ESP32. Anyone with web_server
  enabled and HTTP basic auth configured on version 2021.9.1 or older is vulnerable
  to an issue in which `web_server` allows over-the-air (OTA) updates without checking
  user defined basic auth username & password. This issue is patched in version 2021.9.2.
  As a workaround, one may disable or remove `web_server`.
affected:
- package:
    name: esphome
    ecosystem: PyPI
  ranges:
  - type: GIT
    repo: https://github.com/esphome/esphome
    events:
    - introduced: '0'
    - fixed: 2234f6aacf8cc653307fed80f3750317a82c4f83
  - type: ECOSYSTEM
    events: 
      - introduced: "0"
      - fixed: "2021.9.2"
references:
- type: FIX
  url: https://github.com/esphome/esphome/commit/2234f6aacf8cc653307fed80f3750317a82c4f83
- type: WEB
  url: https://github.com/esphome/esphome/pull/2409/commits/207cde1667d8c799a197b78ca8a5a14de8d5ca1e
- type: WEB
  url: https://github.com/esphome/esphome/releases/tag/2021.9.2
- type: ADVISORY
  url: https://github.com/esphome/esphome/security/advisories/GHSA-48mj-p7x2-5jfm
aliases:
- CVE-2021-41104
modified: "2021-09-28T16:30:00Z"
published: "2021-09-28T16:15:00Z"
